In [23]:
import tensorflow as tf

In [24]:
a = tf.constant(2.3, dtype=tf.float32)
a

<tf.Tensor 'Const_2:0' shape=() dtype=float32>

In [25]:
b = tf.Variable(3)
b

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


<tf.Variable 'Variable:0' shape=() dtype=int32>

In [26]:
b = 5

In [27]:
b

5

In [28]:
c = tf.add(a, b)
c

<tf.Tensor 'Add_1:0' shape=() dtype=float32>

In [29]:
init_op = tf.compat.v1.global_variables_initializer()

In [30]:
tf.compat.v1.disable_eager_execution()

In [31]:
hello = tf.constant("Hello")
world = tf.constant("world")

In [32]:
hello_world = tf.add(hello, world)

In [33]:
sess = tf.compat.v1.Session()
sess.run(init_op)
print(sess.run(hello_world))

b'Helloworld'


In [34]:
d = tf.compat.v1.placeholder(tf.float32)

In [35]:
b = d*2

In [36]:
result_1 = sess.run(b, feed_dict={d: 3})
print(result_1)

6.0


In [37]:
result_2 = sess.run(b, feed_dict={d:[3,5,7]})
print(result_2)

[ 6. 10. 14.]


In [38]:
result_2 = sess.run(b, feed_dict={d:[[3,5,7],[6,7,8]]})
print(result_2)

[[ 6. 10. 14.]
 [12. 14. 16.]]


In [39]:
dictionary = {d:[[3,5,7],[6,7,8]]}

In [40]:
result_2 = sess.run(b, feed_dict=dictionary)
print(result_2)

[[ 6. 10. 14.]
 [12. 14. 16.]]


In [41]:
sess.close()

In [42]:
with tf.compat.v1.Session() as sess:
    print(sess.run(hello_world))

b'Helloworld'
