In [1]:
import numpy as np

In [14]:
biases = np.random.randn(2, 3)

In [15]:
biases

array([[ 0.91919473, -1.22393917, -0.55411086],
       [ 0.34031029,  0.42803399,  0.05427363]])

In [16]:
weights = [np.random.randn(y, x) for y, x in  zip([2, 3], [3, 1])]

In [17]:
weights[0]

array([[-0.10295094,  0.81252726, -0.20742495],
       [ 0.57904136,  0.96145757, -0.04621037]])

In [18]:
for b, w in zip(biases, weights):
    print(b)
    print()
    print(w)
    print()

[ 0.91919473 -1.22393917 -0.55411086]

[[-0.10295094  0.81252726 -0.20742495]
 [ 0.57904136  0.96145757 -0.04621037]]

[0.34031029 0.42803399 0.05427363]

[[-0.15121052]
 [ 0.52704403]
 [-1.33481192]]



In [20]:
for i in range(0, 100, 10):
    print(i)

0
10
20
30
40
50
60
70
80
90
