In [1]:
import numpy as np

np.random.seed(0)

In [44]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases

In [45]:
layer1 = Layer_Dense(4, 7)

In [46]:
layer2 = Layer_Dense(7, 5)

In [54]:
layer1.weights.shape

(4, 7)

In [47]:
inputs = [[1,2,3,2.5],
         [2, 5, -1, 2],
         [-1.5, 2.7, 3.3, -0.8]]

In [48]:
layer1.forward(inputs)

In [49]:
layer1.outputs

array([[-0.71223492, -0.04068305,  0.3945003 ,  0.77915842,  0.42598354,
         0.31925354,  0.07098979],
       [-0.10497014, -0.09501059,  0.15535194,  0.50456333,  0.10469234,
         0.40056065,  0.88175426],
       [-0.62627028, -0.22490529, -0.29352748,  0.58473837,  0.22854013,
         0.24703089,  0.05684194]])

In [50]:
layer2.forward(layer1.outputs)

In [51]:
layer2.outputs

array([[ 0.10822823, -0.12997732,  0.33850163,  0.20884027, -0.13535682],
       [ 0.03812671, -0.14804536, -0.00303935,  0.20681901,  0.00061867],
       [ 0.02145218, -0.10473051,  0.20033334,  0.06992759, -0.0332431 ]])

In [52]:
np.zeros((1, 4))

array([[0., 0., 0., 0.]])

In [ ]:
class ActivationReLU:
    def forward(self, input):
        self.output = np.maximum(0, inputs)